//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://localhost/", ClrNamespace = "Mictlanix.ProFact.Client.Internals.V32")]

namespace Mictlanix.ProFact.Client.Internals.V32
{
	using System.Runtime.Serialization;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfAnyType", Namespace = "http://localhost/", ItemName = "anyType")]
	internal class ArrayOfAnyType : System.Collections.Generic.List<object>
	{
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://localhost/", ConfigurationName = "Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap")]
	internal interface TimbradoSoap
	{

		// CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
		[System.ServiceModel.OperationContractAttribute(Action = "http://localhost/RegistraEmisor", ReplyAction = "*")]
		Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorResponse RegistraEmisor(Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorRequest request);

		// CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
		[System.ServiceModel.OperationContractAttribute(Action = "http://localhost/TimbraRetencion", ReplyAction = "*")]
		Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionResponse TimbraRetencion(Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionRequest request);

		// CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
		[System.ServiceModel.OperationContractAttribute(Action = "http://localhost/TimbraCFDI", ReplyAction = "*")]
		Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIResponse TimbraCFDI(Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIRequest request);

		// CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
		[System.ServiceModel.OperationContractAttribute(Action = "http://localhost/CancelaCFDI", ReplyAction = "*")]
		Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIResponse CancelaCFDI(Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIRequest request);

		// CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
		[System.ServiceModel.OperationContractAttribute(Action = "http://localhost/CancelaCFDIAck", ReplyAction = "*")]
		Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckResponse CancelaCFDIAck(Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckRequest request);

		// CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
		[System.ServiceModel.OperationContractAttribute(Action = "http://localhost/CancelaRetencion", ReplyAction = "*")]
		Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionResponse CancelaRetencion(Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionRequest request);

		// CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
		[System.ServiceModel.OperationContractAttribute(Action = "http://localhost/ObtieneCFDI", ReplyAction = "*")]
		Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIResponse ObtieneCFDI(Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIRequest request);

		// CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
		[System.ServiceModel.OperationContractAttribute(Action = "http://localhost/ObtieneRetencion", ReplyAction = "*")]
		Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionResponse ObtieneRetencion(Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionRequest request);
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class RegistraEmisorRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "RegistraEmisor", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorRequestBody Body;

		public RegistraEmisorRequest()
		{
		}

		public RegistraEmisorRequest(Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorRequestBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class RegistraEmisorRequestBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public string usuarioIntegrador;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
		public string rfcEmisor;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
		public string base64Cer;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
		public string base64Key;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
		public string contrasena;

		public RegistraEmisorRequestBody()
		{
		}

		public RegistraEmisorRequestBody(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena)
		{
			this.usuarioIntegrador = usuarioIntegrador;
			this.rfcEmisor = rfcEmisor;
			this.base64Cer = base64Cer;
			this.base64Key = base64Key;
			this.contrasena = contrasena;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class RegistraEmisorResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "RegistraEmisorResponse", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorResponseBody Body;

		public RegistraEmisorResponse()
		{
		}

		public RegistraEmisorResponse(Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorResponseBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class RegistraEmisorResponseBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType RegistraEmisorResult;

		public RegistraEmisorResponseBody()
		{
		}

		public RegistraEmisorResponseBody(Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType RegistraEmisorResult)
		{
			this.RegistraEmisorResult = RegistraEmisorResult;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class TimbraRetencionRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "TimbraRetencion", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionRequestBody Body;

		public TimbraRetencionRequest()
		{
		}

		public TimbraRetencionRequest(Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionRequestBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class TimbraRetencionRequestBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public string usuarioIntegrador;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
		public string xmlComprobanteBase64;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
		public string idComprobante;

		public TimbraRetencionRequestBody()
		{
		}

		public TimbraRetencionRequestBody(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante)
		{
			this.usuarioIntegrador = usuarioIntegrador;
			this.xmlComprobanteBase64 = xmlComprobanteBase64;
			this.idComprobante = idComprobante;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class TimbraRetencionResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "TimbraRetencionResponse", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionResponseBody Body;

		public TimbraRetencionResponse()
		{
		}

		public TimbraRetencionResponse(Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionResponseBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class TimbraRetencionResponseBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType TimbraRetencionResult;

		public TimbraRetencionResponseBody()
		{
		}

		public TimbraRetencionResponseBody(Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType TimbraRetencionResult)
		{
			this.TimbraRetencionResult = TimbraRetencionResult;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class TimbraCFDIRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "TimbraCFDI", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIRequestBody Body;

		public TimbraCFDIRequest()
		{
		}

		public TimbraCFDIRequest(Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIRequestBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class TimbraCFDIRequestBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public string usuarioIntegrador;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
		public string xmlComprobanteBase64;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
		public string idComprobante;

		public TimbraCFDIRequestBody()
		{
		}

		public TimbraCFDIRequestBody(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante)
		{
			this.usuarioIntegrador = usuarioIntegrador;
			this.xmlComprobanteBase64 = xmlComprobanteBase64;
			this.idComprobante = idComprobante;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class TimbraCFDIResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "TimbraCFDIResponse", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIResponseBody Body;

		public TimbraCFDIResponse()
		{
		}

		public TimbraCFDIResponse(Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIResponseBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class TimbraCFDIResponseBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType TimbraCFDIResult;

		public TimbraCFDIResponseBody()
		{
		}

		public TimbraCFDIResponseBody(Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType TimbraCFDIResult)
		{
			this.TimbraCFDIResult = TimbraCFDIResult;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class CancelaCFDIRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "CancelaCFDI", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIRequestBody Body;

		public CancelaCFDIRequest()
		{
		}

		public CancelaCFDIRequest(Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIRequestBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class CancelaCFDIRequestBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public string usuarioIntegrador;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
		public string rfcEmisor;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
		public string folioUUID;

		public CancelaCFDIRequestBody()
		{
		}

		public CancelaCFDIRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			this.usuarioIntegrador = usuarioIntegrador;
			this.rfcEmisor = rfcEmisor;
			this.folioUUID = folioUUID;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class CancelaCFDIResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "CancelaCFDIResponse", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIResponseBody Body;

		public CancelaCFDIResponse()
		{
		}

		public CancelaCFDIResponse(Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIResponseBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class CancelaCFDIResponseBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType CancelaCFDIResult;

		public CancelaCFDIResponseBody()
		{
		}

		public CancelaCFDIResponseBody(Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType CancelaCFDIResult)
		{
			this.CancelaCFDIResult = CancelaCFDIResult;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class CancelaCFDIAckRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "CancelaCFDIAck", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckRequestBody Body;

		public CancelaCFDIAckRequest()
		{
		}

		public CancelaCFDIAckRequest(Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckRequestBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class CancelaCFDIAckRequestBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public string usuarioIntegrador;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
		public string rfcEmisor;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
		public string folioUUID;

		public CancelaCFDIAckRequestBody()
		{
		}

		public CancelaCFDIAckRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			this.usuarioIntegrador = usuarioIntegrador;
			this.rfcEmisor = rfcEmisor;
			this.folioUUID = folioUUID;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class CancelaCFDIAckResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "CancelaCFDIAckResponse", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckResponseBody Body;

		public CancelaCFDIAckResponse()
		{
		}

		public CancelaCFDIAckResponse(Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckResponseBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class CancelaCFDIAckResponseBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType CancelaCFDIAckResult;

		public CancelaCFDIAckResponseBody()
		{
		}

		public CancelaCFDIAckResponseBody(Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType CancelaCFDIAckResult)
		{
			this.CancelaCFDIAckResult = CancelaCFDIAckResult;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class CancelaRetencionRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "CancelaRetencion", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionRequestBody Body;

		public CancelaRetencionRequest()
		{
		}

		public CancelaRetencionRequest(Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionRequestBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class CancelaRetencionRequestBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public string usuarioIntegrador;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
		public string rfcEmisor;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
		public string folioUUID;

		public CancelaRetencionRequestBody()
		{
		}

		public CancelaRetencionRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			this.usuarioIntegrador = usuarioIntegrador;
			this.rfcEmisor = rfcEmisor;
			this.folioUUID = folioUUID;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class CancelaRetencionResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "CancelaRetencionResponse", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionResponseBody Body;

		public CancelaRetencionResponse()
		{
		}

		public CancelaRetencionResponse(Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionResponseBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class CancelaRetencionResponseBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType CancelaRetencionResult;

		public CancelaRetencionResponseBody()
		{
		}

		public CancelaRetencionResponseBody(Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType CancelaRetencionResult)
		{
			this.CancelaRetencionResult = CancelaRetencionResult;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class ObtieneCFDIRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "ObtieneCFDI", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIRequestBody Body;

		public ObtieneCFDIRequest()
		{
		}

		public ObtieneCFDIRequest(Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIRequestBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class ObtieneCFDIRequestBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public string usuarioIntegrador;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
		public string rfcEmisor;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
		public string folioUUID;

		public ObtieneCFDIRequestBody()
		{
		}

		public ObtieneCFDIRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			this.usuarioIntegrador = usuarioIntegrador;
			this.rfcEmisor = rfcEmisor;
			this.folioUUID = folioUUID;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class ObtieneCFDIResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "ObtieneCFDIResponse", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIResponseBody Body;

		public ObtieneCFDIResponse()
		{
		}

		public ObtieneCFDIResponse(Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIResponseBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class ObtieneCFDIResponseBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType ObtieneCFDIResult;

		public ObtieneCFDIResponseBody()
		{
		}

		public ObtieneCFDIResponseBody(Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType ObtieneCFDIResult)
		{
			this.ObtieneCFDIResult = ObtieneCFDIResult;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class ObtieneRetencionRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "ObtieneRetencion", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionRequestBody Body;

		public ObtieneRetencionRequest()
		{
		}

		public ObtieneRetencionRequest(Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionRequestBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class ObtieneRetencionRequestBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public string usuarioIntegrador;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
		public string rfcEmisor;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
		public string folioUUID;

		public ObtieneRetencionRequestBody()
		{
		}

		public ObtieneRetencionRequestBody(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			this.usuarioIntegrador = usuarioIntegrador;
			this.rfcEmisor = rfcEmisor;
			this.folioUUID = folioUUID;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	internal partial class ObtieneRetencionResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "ObtieneRetencionResponse", Namespace = "http://localhost/", Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionResponseBody Body;

		public ObtieneRetencionResponse()
		{
		}

		public ObtieneRetencionResponse(Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionResponseBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://localhost/")]
	internal partial class ObtieneRetencionResponseBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType ObtieneRetencionResult;

		public ObtieneRetencionResponseBody()
		{
		}

		public ObtieneRetencionResponseBody(Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType ObtieneRetencionResult)
		{
			this.ObtieneRetencionResult = ObtieneRetencionResult;
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	internal interface TimbradoSoapChannel : Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
	internal partial class TimbradoSoapClient : System.ServiceModel.ClientBase<Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap>, Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap
	{

		public TimbradoSoapClient()
		{
		}

		public TimbradoSoapClient(string endpointConfigurationName) :
			base(endpointConfigurationName)
		{
		}

		public TimbradoSoapClient(string endpointConfigurationName, string remoteAddress) :
			base(endpointConfigurationName, remoteAddress)
		{
		}

		public TimbradoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
			base(endpointConfigurationName, remoteAddress)
		{
		}

		public TimbradoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
			base(binding, remoteAddress)
		{
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorResponse Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap.RegistraEmisor(Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorRequest request)
		{
			return base.Channel.RegistraEmisor(request);
		}

		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType RegistraEmisor(string usuarioIntegrador, string rfcEmisor, string base64Cer, string base64Key, string contrasena)
		{
			Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorRequest inValue = new Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorRequest();
			inValue.Body = new Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorRequestBody();
			inValue.Body.usuarioIntegrador = usuarioIntegrador;
			inValue.Body.rfcEmisor = rfcEmisor;
			inValue.Body.base64Cer = base64Cer;
			inValue.Body.base64Key = base64Key;
			inValue.Body.contrasena = contrasena;
			Mictlanix.ProFact.Client.Internals.V32.RegistraEmisorResponse retVal = ((Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap)(this)).RegistraEmisor(inValue);
			return retVal.Body.RegistraEmisorResult;
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionResponse Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap.TimbraRetencion(Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionRequest request)
		{
			return base.Channel.TimbraRetencion(request);
		}

		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType TimbraRetencion(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante)
		{
			Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionRequest inValue = new Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionRequest();
			inValue.Body = new Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionRequestBody();
			inValue.Body.usuarioIntegrador = usuarioIntegrador;
			inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
			inValue.Body.idComprobante = idComprobante;
			Mictlanix.ProFact.Client.Internals.V32.TimbraRetencionResponse retVal = ((Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap)(this)).TimbraRetencion(inValue);
			return retVal.Body.TimbraRetencionResult;
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIResponse Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap.TimbraCFDI(Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIRequest request)
		{
			return base.Channel.TimbraCFDI(request);
		}

		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType TimbraCFDI(string usuarioIntegrador, string xmlComprobanteBase64, string idComprobante)
		{
			Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIRequest inValue = new Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIRequest();
			inValue.Body = new Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIRequestBody();
			inValue.Body.usuarioIntegrador = usuarioIntegrador;
			inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64;
			inValue.Body.idComprobante = idComprobante;
			Mictlanix.ProFact.Client.Internals.V32.TimbraCFDIResponse retVal = ((Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap)(this)).TimbraCFDI(inValue);
			return retVal.Body.TimbraCFDIResult;
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIResponse Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap.CancelaCFDI(Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIRequest request)
		{
			return base.Channel.CancelaCFDI(request);
		}

		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType CancelaCFDI(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIRequest inValue = new Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIRequest();
			inValue.Body = new Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIRequestBody();
			inValue.Body.usuarioIntegrador = usuarioIntegrador;
			inValue.Body.rfcEmisor = rfcEmisor;
			inValue.Body.folioUUID = folioUUID;
			Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIResponse retVal = ((Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap)(this)).CancelaCFDI(inValue);
			return retVal.Body.CancelaCFDIResult;
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckResponse Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap.CancelaCFDIAck(Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckRequest request)
		{
			return base.Channel.CancelaCFDIAck(request);
		}

		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType CancelaCFDIAck(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckRequest inValue = new Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckRequest();
			inValue.Body = new Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckRequestBody();
			inValue.Body.usuarioIntegrador = usuarioIntegrador;
			inValue.Body.rfcEmisor = rfcEmisor;
			inValue.Body.folioUUID = folioUUID;
			Mictlanix.ProFact.Client.Internals.V32.CancelaCFDIAckResponse retVal = ((Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap)(this)).CancelaCFDIAck(inValue);
			return retVal.Body.CancelaCFDIAckResult;
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionResponse Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap.CancelaRetencion(Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionRequest request)
		{
			return base.Channel.CancelaRetencion(request);
		}

		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType CancelaRetencion(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionRequest inValue = new Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionRequest();
			inValue.Body = new Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionRequestBody();
			inValue.Body.usuarioIntegrador = usuarioIntegrador;
			inValue.Body.rfcEmisor = rfcEmisor;
			inValue.Body.folioUUID = folioUUID;
			Mictlanix.ProFact.Client.Internals.V32.CancelaRetencionResponse retVal = ((Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap)(this)).CancelaRetencion(inValue);
			return retVal.Body.CancelaRetencionResult;
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIResponse Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap.ObtieneCFDI(Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIRequest request)
		{
			return base.Channel.ObtieneCFDI(request);
		}

		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType ObtieneCFDI(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIRequest inValue = new Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIRequest();
			inValue.Body = new Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIRequestBody();
			inValue.Body.usuarioIntegrador = usuarioIntegrador;
			inValue.Body.rfcEmisor = rfcEmisor;
			inValue.Body.folioUUID = folioUUID;
			Mictlanix.ProFact.Client.Internals.V32.ObtieneCFDIResponse retVal = ((Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap)(this)).ObtieneCFDI(inValue);
			return retVal.Body.ObtieneCFDIResult;
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionResponse Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap.ObtieneRetencion(Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionRequest request)
		{
			return base.Channel.ObtieneRetencion(request);
		}

		public Mictlanix.ProFact.Client.Internals.V32.ArrayOfAnyType ObtieneRetencion(string usuarioIntegrador, string rfcEmisor, string folioUUID)
		{
			Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionRequest inValue = new Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionRequest();
			inValue.Body = new Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionRequestBody();
			inValue.Body.usuarioIntegrador = usuarioIntegrador;
			inValue.Body.rfcEmisor = rfcEmisor;
			inValue.Body.folioUUID = folioUUID;
			Mictlanix.ProFact.Client.Internals.V32.ObtieneRetencionResponse retVal = ((Mictlanix.ProFact.Client.Internals.V32.TimbradoSoap)(this)).ObtieneRetencion(inValue);
			return retVal.Body.ObtieneRetencionResult;
		}
	}
}

